// <auto-generated />
using HospitalManagement.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramworkCRUD2.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20231208154229_Hospital Migration Dbase")]
    partial class HospitalMigrationDbase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HospitalManagement.data.Hospital", b =>
                {
                    b.Property<int>("Patient_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Patient_Age")
                        .HasColumnType("int");

                    b.Property<string>("Patient_Disease")
                        .HasColumnType("longtext");

                    b.Property<string>("Patient_Name")
                        .HasColumnType("longtext");

                    b.HasKey("Patient_Id");

                    b.ToTable("HospitalAdmin");
                });
#pragma warning restore 612, 618
        }
    }
}
